steps:
  - id: Build Container
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_APP_IMAGE:$SHORT_SHA", "."]
  - id: Push Container
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_APP_IMAGE:$SHORT_SHA"]
  - id: Update Cloud Run service
    name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run",
        "services",
        "update",
        "$_SERVICE",
        "--platform=managed",
        "--image=$_APP_IMAGE:$SHORT_SHA",
        "--region=$_REGION",
        "--quiet",
        "--async",
      ]
