title = "PS API Database Seed Data"

[characters]

[characters.1]
age = 15
born = "AW 327, 5.25"
game = "https://psapi.dev/api/game/1/"
name = "Alis Landale"
race = "Human"
spells = ["Heal", "Bye", "Chat", "Fire", "Rope", "Fly"]

[characters.2]
gender = "Male"
game = "https://psapi.dev/api/game/1/"
race = "Musk Cat"
spells = ["Cure", "Exit", "Help", "Terrify", "Trap", "Wall"]

[characters.3]
age = 28
born = "AW 314, 2.26"
game = "https://psapi.dev/api/game/1/"
name = "Odin"
race = "Human"

[characters.4]
age = 27
born = "AW 315, 3.24"
game = "https://psapi.dev/api/game/1/"
name = "Noah"
race = "Human"
spells = [
  "Fire",
  "Cure",
  "Exit",
  "Open",
  "Prot",
  "Rise",
  "Tele",
  "Thun",
  "Wind",
]

[characters.5]
game = "https://psapi.dev/api/game/2/"
name = "Rolf"
race = "Human"
spells = ["Foi", "Res", "Ryuka", "Gifoi"]

[characters.6]
game = "https://psapi.dev/api/game/2/"
name = "Nei"
race = "Numan"
spells = ["Res", "Anti", "Sak", "Nasak"]

[characters.7]
game = "https://psapi.dev/api/game/2/"
name = "Rudo"
race = "Human"

[games]

[games.1]
title = "Phantasy Star"
title_japanese = "ファンタシースター"
released = "1987-12-20"
platforms = ["Sega Master System"]
characters = [
  "https://psapi.dev/api/character/1/",
  "https://psapi.dev/api/character/2/",
  "https://psapi.dev/api/character/3/",
  "https://psapi.dev/api/character/4/",
]

[games.2]
title = "Phantasy Star II"
title_japanese = "ファンタシースターII 還らざる時の終わりに"
released = "1989-03-21"
platforms = ["Sega Genesis", "Sega Mega Drive"]
characters = [
  "https://psapi.dev/api/character/5/",
  "https://psapi.dev/api/character/6/",
  "https://psapi.dev/api/character/7/",
]
